p = "src/client/shell/tests/agents_worktrees_notifications.rs"
s = open(p).read()
old = "fn mouse_hits_use_stable_workspace_tab_and_pane_ids() {"
dot = chr(0xB7)
capture = (
    "fn capture_workspace_tag_modes() {\n"
    "    let mut snapshot = snapshot();\n"
    "    snapshot.workspaces[0].worktree = Some(ClientShellWorktree {\n"
    "        key: \"repo\".into(),\n"
    "        label: \"repo\".into(),\n"
    "        is_linked_worktree: false,\n"
    "    });\n"
    "    snapshot.workspaces.push(ClientShellWorkspace {\n"
    "        workspace_id: \"ws_22\".into(),\n"
    "        active_tab_id: \"tab_ws2\".into(),\n"
    "        new_workspace_cwd: \"/repo/feature\".into(),\n"
    "        number: 2,\n"
    "        label: \"repo-feature\".into(),\n"
    "        custom_label: false,\n"
    "        branch: Some(\"worktree/feature\".into()),\n"
    "        git_ahead_behind: None,\n"
    "        tokens: Vec::new(),\n"
    "        worktree: Some(ClientShellWorktree {\n"
    "            key: \"repo\".into(),\n"
    "            label: \"repo\".into(),\n"
    "            is_linked_worktree: true,\n"
    "        }),\n"
    "        focused: false,\n"
    "        agent_status: AgentStatus::Idle,\n"
    "    });\n"
    "    let mut out = String::new();\n"
    "    for show in [false, true] {\n"
    "        let mut config = ClientShellConfig::from_config(&Config::default());\n"
    "        config.spaces.show_workspace_ids = show;\n"
    "        let mut state = ClientShellState::new(config);\n"
    "        state.set_snapshot(Box::new(snapshot.clone()));\n"
    "        state.set_pane_surface(surface());\n"
    "        let frame = state.compose(106, 20).expect(\"frame\");\n"
    "        out.push_str(&format!(\"\\n=== show_workspace_ids = {show} ===\\n\"));\n"
    "        for row in frame.cells.chunks(frame.width as usize) {\n"
    "            let line: String = row\n"
    "                .iter()\n"
    "                .map(|cell| cell.symbol.as_str())\n"
    "                .collect::<String>();\n"
    "            out.push_str(&line.replace(' ', \"%DOT%\"));\n"
    "            out.push('\\n');\n"
    "        }\n"
    "    }\n"
    "    std::fs::write(\"/tmp/sidebar-captures/labels.txt\", &out).expect(\"write capture\");\n"
    "}\n"
    "\n"
)
capture = capture.replace("%DOT%", dot)
assert s.count(old) == 1
open(p, "w").write(s.replace(old, capture + old, 1))
print("inserted")
